trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

variables:
  resourceGroupName: DefaultResourceGroup-CUS
  azureResourceManagerConnection: 'servicePrincipal-Azure'
  subscriptionId: 2cf64833-1e9f-4e52-ab37-4e7ea0e77717

stages:
- stage: Provision
  jobs:
  - job: FunctionApp
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureResourceManagerConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '**/Azure/AzureFunctionApp.json.json'
        deploymentMode: 'Incremental'
