trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016

extends:
  template:  ${{variables['System.DefaultWorkingDirectory']}}/template_build_dotnet.yml
  parameters:
    projectPath: '**/*.sln'

    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      extraParameter: 'null'
