# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
  - job:
    steps: 
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Create Resource Group'
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'Azure subscription 1(2cf64833-1e9f-4e52-ab37-4e7ea0e77717)'
        subscriptionId: '2cf64833-1e9f-4e52-ab37-4e7ea0e77717'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '**/Azure/ManyInstacesOfSameApp.json'
        deploymentMode: 'Incremental'
    # - task: AzureResourceManagerTemplateDeployment@3
    #   displayName: 'Delete Resource Group'
    #   inputs:
    #     deploymentScope: 'Resource Group'
    #     azureResourceManagerConnection: 'Azure subscription 1(2cf64833-1e9f-4e52-ab37-4e7ea0e77717)'
    #     subscriptionId: '2cf64833-1e9f-4e52-ab37-4e7ea0e77717'
    #     action: 'DeleteRG'
    #     resourceGroupName: 'sean-phillips-demo'