trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - npm

stages:
- stage: Provision
  jobs:
  - job: Terraform
    steps:  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'servicePrincipal-Azure'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --location eastus --name TerraformRequirements
          az storage account create --name saterraformrequirements --location eastus --sku Standard_LRS
          az storage container create --name terraform --account-name terraformrequirements
          az storage account keys list -g TerraformRequirements -n saterraformrequirements

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'