trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - npm

stages:
- stage: Provision
  jobs:
  - job: Terraform
    steps:  
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'