trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

variables:
  resourceGroupName: TerraformRequirements
  storageAccountName: saterraformrequirements
  storageContainerName: terraform
  azureServicePrincipal: 'servicePrincipal-Azure'
  subscriptionId: '2cf64833-1e9f-4e52-ab37-4e7ea0e77717'
  armTemplate: '**/TerraformRequirements.json'
  armParameters: '**/parameters.json'

stages:
- stage: Provision
  jobs:
  - job: Terraform
    steps:  

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM Template'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServicePrincipal)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName) '
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: $(armTemplate)
        deploymentMode: 'Incremental'
        deploymentOutputs: 'output'    
    - pwsh: |
        $outputsObject = $env:output | ConvertFrom-Json
        Write-Host "##vso[task.setvariable variable=storageAccountKey]$($outputsObject.storageAccountKey.value)"
    - pwsh: |
        echo $(storageAccountKey)
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        backendServiceArm: 'servicePrincipal-Azure'
        backendAzureRmResourceGroupName: '$(resourceGroupName)'
        backendAzureRmStorageAccountName: '$(storageAccountName)'
        backendAzureRmContainerName: '$(storageContainerName)'
        backendAzureRmKey: '$(storageAccountKey)'
