trigger:
  batch: true
  branches:
    include:
    - main

pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

variables:
  resourceGroupName: TerraformRequirements
  storageAccountName: saterraformrequirements
  storageContainerName: terraform


stages:
- stage: Provision
  jobs:
  - job: Terraform
    steps:  
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'servicePrincipal-Azure'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --location eastus --name $(resourceGroupName)
          az storage account create --name $(storageAccountName) --location eastus --sku Standard_LRS --resource-group $(resourceGroupName)
          az storage container create --name $(storageContainerName) --account-name $(storageAccountName) --resource-group $(resourceGroupName)
          az storage account keys list -g $(resourceGroupName) -n $(storageAccountName) 
 
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'servicePrincipal-Azure'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
        $key =(Get-AzureRMStorageAccountKey -ResourceGroupName $(resourceGroupName) -AccountName $(storageAccountName)).value(0)
        Write-Host "##vso[task.setvariable variable=storagekey]$key"
   
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
        backendServiceArm: 'servicePrincipal-Azure'
        backendAzureRmResourceGroupName: '$(resourceGroupName)'
        backendAzureRmStorageAccountName: '$(storageAccountName)'
        backendAzureRmContainerName: '$(storageContainerName)'
        backendAzureRmKey: 'idk'

